"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.codeEditorRouter = void 0;
const express_1 = require("express");
const codeEditorController_1 = require("../controllers/codeEditorController");
const verifyToken_1 = require("../middlewares/verifyToken");
// import { verifyTokenAnonymous } from "../middlewares/verifyTokenAnonymous";
exports.codeEditorRouter = (0, express_1.Router)();
exports.codeEditorRouter.post("/save", verifyToken_1.verifyToken, codeEditorController_1.saveCode);
exports.codeEditorRouter.post("/load", verifyToken_1.verifyToken, codeEditorController_1.loadCode);
exports.codeEditorRouter.delete("/delete/:id", verifyToken_1.verifyToken, codeEditorController_1.deleteCode);
exports.codeEditorRouter.put("/edit/:id", verifyToken_1.verifyToken, codeEditorController_1.editCode);
exports.codeEditorRouter.get("/my-repositories", verifyToken_1.verifyToken, codeEditorController_1.getMyCodes);
exports.codeEditorRouter.get("/all-repositories", verifyToken_1.verifyToken, codeEditorController_1.getAllCodes);
